// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_f76e0JfpQm33z0lR-2W9-RiUYc0Wmw8',
    appId: '1:940448057923:web:b71a67a38c82fe9bdda2f6',
    messagingSenderId: '940448057923',
    projectId: 'harmony-5110f',
    authDomain: 'harmony-5110f.firebaseapp.com',
    storageBucket: 'harmony-5110f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJvjgF-yJsFPrxn2GImAZRkcMURWG8T00',
    appId: '1:940448057923:android:31da43646c8154a7dda2f6',
    messagingSenderId: '940448057923',
    projectId: 'harmony-5110f',
    storageBucket: 'harmony-5110f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJRFmSgaYCWzhhRq7hWee1i9Y0mlddzfw',
    appId: '1:940448057923:ios:31ca2f16eeacad37dda2f6',
    messagingSenderId: '940448057923',
    projectId: 'harmony-5110f',
    storageBucket: 'harmony-5110f.firebasestorage.app',
    iosBundleId: 'com.example.damMusicStreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJRFmSgaYCWzhhRq7hWee1i9Y0mlddzfw',
    appId: '1:940448057923:ios:31ca2f16eeacad37dda2f6',
    messagingSenderId: '940448057923',
    projectId: 'harmony-5110f',
    storageBucket: 'harmony-5110f.firebasestorage.app',
    iosBundleId: 'com.example.damMusicStreaming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_f76e0JfpQm33z0lR-2W9-RiUYc0Wmw8',
    appId: '1:940448057923:web:3cea9b42ed65e169dda2f6',
    messagingSenderId: '940448057923',
    projectId: 'harmony-5110f',
    authDomain: 'harmony-5110f.firebaseapp.com',
    storageBucket: 'harmony-5110f.firebasestorage.app',
  );

}