services:
  db-harmony:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234 
      POSTGRES_DB: harmony
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 20s
      retries: 10
    ports:
      - 5454:5432