services:
  db-harmony:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harmony
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 20s
      timeout: 20s
      retries: 10
    ports:
      - 5454:5432

  cloudflared-harmony:
    image: cloudflare/cloudflared
    container_name: cloudflared_harmony
    environment:
      - TZ=Brazil/Recife
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    depends_on:
      - db-harmony
